version: "3.7"
services:
  app:
    env_file: .env
    build: .
    ports:
      - 8070:8070
  db:
    image: postgres:9
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
